language: go

services:
  - elasticsearch
  - mysql

sudo: true

go:
  - "1.8" 
  - "1.9"
  - "1.10" # travis parses 1.10 as 1.1
  - "release"
  - "tip" 

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client  

env:
  - DEP_VERSION="0.4.1"  

before_install:
  # Create MySQL database
  - mysql -e 'CREATE DATABASE services;'
  # Download and install ElasticSearch binary
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.1.1.deb && sudo dpkg -i --force-confnew elasticsearch-6.1.1.deb && sudo service elasticsearch restart
  # Download the binary to bin folder in $GOPATH
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  # Make the binary executable
  - chmod +x $GOPATH/bin/dep

install:
  # install golint
 - go get -u github.com/golang/lint/golint
 - go get github.com/modocache/gover
 - dep ensure

before_script:
  - sleep 10

script:
  # build golang binary
  - make build
  # create elasticsearch index
  - make setup force=true
  # Run the unit tests suite
  - go test -v ./...
  # Collect coverage reports
  - go list -f '{{if len .TestGoFiles}}"go test -coverprofile={{.Dir}}/.coverprofile {{.ImportPath}}"{{end}}' ./... | xargs -i sh -c {}
  # Merge coverage reports
  - gover . coverprofile.txt
