version: '2'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    container_name: es
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 3g
    volumes:
      - esdata3:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:6.1.1
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://es:9200
    ports:
      - 5601:5601
    links:
      - es
    networks:
      - esnet

volumes:
  esdata3:
    driver: local

networks:
  esnet:
